# Generated by Django 5.2.8 on 2025-12-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='الشركة المصنعة')),
                ('model_name', models.CharField(max_length=50, verbose_name='الموديل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر اليومي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
