# Generated by Django 5.2.8 on 2025-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاحة للإيجار؟'),
        ),
    ]
