# Generated by Django 5.2.8 on 2025-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_car_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='أبيض', max_length=20, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'بنزين'), ('diesel', 'ديزل'), ('hybrid', 'هجين'), ('electric', 'كهرباء')], default='petrol', max_length=10, verbose_name='نوع الوقود'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default='XXX 0000', max_length=20, unique=True, verbose_name='رقم اللوحة'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('auto', 'أوتوماتيك'), ('manual', 'عادي')], default='auto', max_length=10, verbose_name='ناقل الحركة'),
        ),
    ]
