# Generated by Django 5.2.8 on 2025-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(choices=[('RIYADH_AIRPORT', 'مطار الرياض'), ('RIYADH_DOWNTOWN', 'وسط الرياض'), ('JEDDAH_AIRPORT', 'مطار جدة'), ('DAMMAM_AIRPORT', 'مطار الدمام'), ('MAIN_OFFICE', 'المقر الرئيسي')], default='MAIN_OFFICE', max_length=50, verbose_name='موقع التسليم'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(choices=[('RIYADH_AIRPORT', 'مطار الرياض'), ('RIYADH_DOWNTOWN', 'وسط الرياض'), ('JEDDAH_AIRPORT', 'مطار جدة'), ('DAMMAM_AIRPORT', 'مطار الدمام'), ('MAIN_OFFICE', 'المقر الرئيسي')], default='MAIN_OFFICE', max_length=50, verbose_name='موقع الاستلام'),
        ),
    ]
