# Generated by Django 5.2.8 on 2025-12-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_dropoff_location_booking_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط عرض التسليم'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط طول التسليم'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط عرض الاستلام'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط طول الاستلام'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(default='Main Office', max_length=255, verbose_name='موقع التسليم (العنوان)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(default='Main Office', max_length=255, verbose_name='موقع الاستلام (العنوان)'),
        ),
    ]
