# Generated by Django 5.2.7 on 2025-12-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_duration_days_alter_booking_total_price'),
        ('bookings', '0003_booking_dropoff_lat_booking_dropoff_lng_and_more'),
    ]

    operations = [
    ]
